--SELECT PARTNER_ID, NAME, BRAND FROM [dotzcloud-datalabs-uat:SKU.1300] WHERE NAME LIKE '%PICANHA%' AND NAME LIKE '%FRIBOI%'
--SELECT PARTNER_ID FROM [dotzcloud-datalabs-uat:SKU.1300] WHERE NAME LIKE '%PICANHA%' AND NAME LIKE '%FRIBOI%'  GROUP BY PARTNER_ID  --, NAME, BRAND

SELECT PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME, INTRODUCED_DATE, RETIRED_DATE, UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN 
FROM [dotzcloud-datalabs-uat:SKU.1300] 
WHERE (

(NAME LIKE '%PICANHA%' AND NAME LIKE '%FRIBOI%') AND 
((BRAND LIKE '%FRIBOI%' OR BRAND LIKE '%ANGUS%') OR BRAND IS NULL)
) --AND PARTNER_ID = '19386503' AND NAME LIKE 'PICANHA RESF FRIBOI CX+-25KG%' 
GROUP BY PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME, INTRODUCED_DATE, RETIRED_DATE, UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN

--###############################
--# Tabela OMO_ARIEL_DETERGENTE #
--###############################
SELECT PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME, 
--INTRODUCED_DATE, RETIRED_DATE, 
UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN 
FROM [dotzcloud-datalabs-uat:SKU.1300] 
WHERE (

(NAME LIKE '%OMO%' AND NAME LIKE '%DETERGENTE%' ) OR 
(NAME LIKE '%ARIEL%'))
--OR BRAND LIKE '%ANGUS%') OR BRAND IS NULL) AND PARTNER_ID = '19386503' AND NAME LIKE 'PICANHA RESF FRIBOI CX+-25KG%'

GROUP BY 
PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME,  UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN
--INTRODUCED_DATE, RETIRED_DATE,

--RENAME NOS CAMPOS para  NOVA VERSÃO
SELECT PARTNER_ID as Partner_ID, PRODUCT_ID AS Product_ID, MANUFACTURER_ID AS Brand_ID, CATEGORY_1 AS Category_ID_1, CATEGORY_2 AS Category_ID_2, CATEGORY_3 AS Category_ID_3, 
CATEGORY_4 AS Category_ID_4, NAME AS Product_Name, INTRODUCED_DATE, RETIRED_DATE, UNIT, BRAND AS Brand_Name, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN 
FROM [dotzcloud-datalabs-uat:SKU.1300] 
/*WHERE (

(NAME LIKE '%PICANHA%' AND NAME LIKE '%FRIBOI%') AND 
((BRAND LIKE '%FRIBOI%' OR BRAND LIKE '%ANGUS%') OR BRAND IS NULL)
) --AND PARTNER_ID = '19386503' AND NAME LIKE 'PICANHA RESF FRIBOI CX+-25KG%'*/ 
--GROUP BY PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME, INTRODUCED_DATE, RETIRED_DATE, UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN
GROUP BY PARTNER_ID, PRODUCT_ID, Brand_ID, Category_ID_1, Category_ID_2, Category_ID_3, Category_ID_4, Product_Name, INTRODUCED_DATE, RETIRED_DATE, UNIT, Brand_Name, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN


--PROJETO SANDBOX
--RENAME NOS CAMPOS para  NOVA VERSÃO
SELECT PARTNER_ID as Partner_ID, PRODUCT_ID AS Product_ID, MANUFACTURER_ID AS Brand_ID, CATEGORY_1 AS Category_ID_1, CATEGORY_2 AS Category_ID_2, CATEGORY_3 AS Category_ID_3, 
CATEGORY_4 AS Category_ID_4, NAME AS Product_Name, 
--INTRODUCED_DATE, RETIRED_DATE, 
UNIT, BRAND AS Brand_Name, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN 
FROM [dotzcloud-datalabs-sandbox:SKU.1300] 
/*WHERE (

(NAME LIKE '%PICANHA%' AND NAME LIKE '%FRIBOI%') AND 
((BRAND LIKE '%FRIBOI%' OR BRAND LIKE '%ANGUS%') OR BRAND IS NULL)
) --AND PARTNER_ID = '19386503' AND NAME LIKE 'PICANHA RESF FRIBOI CX+-25KG%'*/ 
--GROUP BY PARTNER_ID, PRODUCT_ID, MANUFACTURER_ID, CATEGORY_1, CATEGORY_2, CATEGORY_3, CATEGORY_4, NAME, INTRODUCED_DATE, RETIRED_DATE, UNIT, BRAND, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN
GROUP BY PARTNER_ID, PRODUCT_ID, Brand_ID, Category_ID_1, Category_ID_2, Category_ID_3, Category_ID_4, Product_Name, 
--INTRODUCED_DATE, RETIRED_DATE, 
UNIT, Brand_Name, PACKAGE_SIZE, PACKAGE_UNIT, PRIVATE_LABEL_FLAG, GTIN
